// Dictionnaire des mots secrets (français, majuscules, sans accents), par longueur.
// Le serveur en tire un au hasard (mode solo, bouton « Aléatoire » du duel).
// Les propositions des joueurs ne sont pas limitées à cette liste : toute suite
// de lettres de la bonne longueur est acceptée.
const BRUT = {
  4: `AIDE AIRE BAIN BANC BLEU BOIS BOUE BRAS CAFE CAGE CHAT CHEF CIEL CLEF COUP COUR CUBE DENT DOUX ECHO FAIM FETE FILM FOIN FOUR GARE GOUT GRIS IDEE JEUX JOUR JUPE LAIT LAVE LIEN LIRE LOUP LUNE MAIN MAIS MARS MERE MIEL MODE MOIS NAGE NOIR NOTE NUIT OEUF ONDE OURS PAIN PAIX PARC PEAU PERE PIED PLAN PONT PORT PRIX REVE RIRE ROBE ROSE ROUE SAGE SALE SENS SOIF SOIR TETE TOIT TOUR TRAM TRIO VENT VERT VIDE VOIE VOIX VRAI YOGA ZERO ZONE BEBE BOUT CAVE CHIC COIN DAME DOME DUNE ETUI FILS GANT LAME LOGE MARE MINE MOTO OPERA PAGE PIPE PLAT PUITS RANG SAUT SOUS TACHE TIGE TUBE VASE VELO VOLE`,
  5: `ARBRE AVION BALLE BANDE BARBE BATON BELLE BIJOU BLANC BRAVE BRUIT CADRE CARTE CHAIR CHANT CHIEN CLOWN COEUR COLLE CORPS COURS CRAIE DANSE DOUCE DROIT ECOLE FERME FLEUR FORET FRERE FROID FRUIT GARDE GLACE GRAND GRAIN HEURE HERBE HUILE IMAGE JAUNE JOUET LAINE LIVRE LOURD MANGE METRO MUSEE NAGER NUAGE ORAGE OUTIL PATTE PIANO PLAGE PLUME POIRE POMME PORTE POUCE RADIO REINE ROUGE ROUTE SABLE SALLE SAUCE SERRE TABLE TASSE TERRE TIGRE TRAIN VACHE VALSE VERRE VIDEO VILLE VIRUS VOILE AMOUR ANGLE ASILE BAGUE BANJO BOEUF BOITE BRISE CABLE CANAL CHAMP CIDRE CREME DRAME ECRAN ENFER FAUNE FILET FOULE FUMEE GEANT HOTEL JOUER LAPIN LEVRE LIBRE LUTIN MAGIE MONDE NOBLE OCEAN OLIVE PAUSE PERLE POULE PRINCE RIVAL ROBOT SALON SAVON SOUPE TAPIS TENTE THEME TOMBE USINE VAGUE ZEBRE`,
  6: `ANIMAL ARGENT AUTOUR BATEAU BOUCHE BOUGIE BUREAU CANARD CARTON CHAISE CHEVAL CIRQUE CLASSE COUSIN DEHORS DESSIN DRAGON ENFANT ETOILE FLAMME GATEAU GENOUX HIBOUX JARDIN JOUEUR MAISON MARCHE MIROIR MONTRE NATURE OISEAU ORANGE PAPIER PARENT PLANTE POULET SOLEIL SOURIS TOMATE VALISE VOYAGE BANANE BOUTON CASQUE ARCHER BALCON BARQUE BERGER BISCUIT BONBON BOTTES BRIQUE CERISE CITRON COCHON COLONNE COMPAS COUSSIN CRAYON DOCTEUR FAUTEUIL FERMIER GLACON GOURDE HAMAC HELICE IGLOO INSECTE JAMBON LAPINS LIMACE MARRON MOUTON NOUILLE OUTILS PALAIS PEINTRE PIRATE POTAGER PRUNES RAISIN RAYONS RENARD ROCHER SALADE SERPENT SORCIER STYLOS TABLES TAMBOUR TIROIR TUNNEL`,
  7: `ABEILLE AMITIE ANIMAUX BALLONS BANANES CAMPING CHAPEAU CHATEAU CUISINE FENETRE FROMAGE GUITARE JARDINS LUNETTE MACHINE MUSIQUE NUAGES PAYSAGE PIRATES PLANETE POISSON RIVIERE TABLEAU TORTUES VOITURE CAROTTE GIRAFES LUMIERE PINCEAU TRESORS VOLCANS WAGONS ARMOIRE BALEINE BRIOCHE CERISES CHEMISE CHOCOLAT COUTEAU DRAPEAU ECHELLE EPINARD FOURMIS GALAXIE GARCONS GOURMAND HORLOGE KIMONO LANTERNE MIROIRS MONTAGNE NAVIRES ORCHIDEE PALMIER PANTALON PEINTURE PISCINE PLUMEAU POMMIER PRINCESSE RAQUETTE RIDEAUX SANDALES SIRENES TELEPHONE TRICOT TROMPETTE VAISSEAU VALISES VOILIER ZEPPELIN`,
};

const MOTS = {};
for (const [len, texte] of Object.entries(BRUT)) {
  const n = Number(len);
  MOTS[n] = [...new Set(texte.split(/\s+/).filter((m) => m.length === n && /^[A-Z]+$/.test(m)))];
}

module.exports = { MOTS };
